"""apply_cascade_rules

Revision ID: 7df4ae5dbfe6
Revises: 8c382b705f8a
Create Date: 2026-07-12 11:15:04.811727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df4ae5dbfe6'
down_revision: Union[str, Sequence[str], None] = '8c382b705f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('environmental_records_user_id_fkey'), 'environmental_records', type_='foreignkey')
    op.create_foreign_key(None, 'environmental_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('governance_records_user_id_fkey'), 'governance_records', type_='foreignkey')
    op.create_foreign_key(None, 'governance_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('saved_reports_user_id_fkey'), 'saved_reports', type_='foreignkey')
    op.create_foreign_key(None, 'saved_reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('social_records_user_id_fkey'), 'social_records', type_='foreignkey')
    op.create_foreign_key(None, 'social_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_badges_user_id_fkey'), 'user_badges', type_='foreignkey')
    op.drop_constraint(op.f('user_badges_badge_id_fkey'), 'user_badges', type_='foreignkey')
    op.create_foreign_key(None, 'user_badges', 'badges', ['badge_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_badges', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_challenges_user_id_fkey'), 'user_challenges', type_='foreignkey')
    op.drop_constraint(op.f('user_challenges_challenge_id_fkey'), 'user_challenges', type_='foreignkey')
    op.create_foreign_key(None, 'user_challenges', 'challenges', ['challenge_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_challenges', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_department_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('users_department_id_fkey'), 'users', 'departments', ['department_id'], ['id'])
    op.drop_constraint(None, 'user_challenges', type_='foreignkey')
    op.drop_constraint(None, 'user_challenges', type_='foreignkey')
    op.create_foreign_key(op.f('user_challenges_challenge_id_fkey'), 'user_challenges', 'challenges', ['challenge_id'], ['id'])
    op.create_foreign_key(op.f('user_challenges_user_id_fkey'), 'user_challenges', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_badges', type_='foreignkey')
    op.drop_constraint(None, 'user_badges', type_='foreignkey')
    op.create_foreign_key(op.f('user_badges_badge_id_fkey'), 'user_badges', 'badges', ['badge_id'], ['id'])
    op.create_foreign_key(op.f('user_badges_user_id_fkey'), 'user_badges', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'social_records', type_='foreignkey')
    op.create_foreign_key(op.f('social_records_user_id_fkey'), 'social_records', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'saved_reports', type_='foreignkey')
    op.create_foreign_key(op.f('saved_reports_user_id_fkey'), 'saved_reports', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'governance_records', type_='foreignkey')
    op.create_foreign_key(op.f('governance_records_user_id_fkey'), 'governance_records', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'environmental_records', type_='foreignkey')
    op.create_foreign_key(op.f('environmental_records_user_id_fkey'), 'environmental_records', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
