"""add_esg_and_gamification_tables

Revision ID: 8c382b705f8a
Revises: 9df30b945cc1
Create Date: 2026-07-12 11:10:50.781379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c382b705f8a'
down_revision: Union[str, Sequence[str], None] = '9df30b945cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_badges_is_active'), 'badges', ['is_active'], unique=False)
    op.create_table('challenges',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('points_reward', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_end_date'), 'challenges', ['end_date'], unique=False)
    op.create_index(op.f('ix_challenges_is_active'), 'challenges', ['is_active'], unique=False)
    op.create_index(op.f('ix_challenges_start_date'), 'challenges', ['start_date'], unique=False)
    op.create_table('environmental_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_records_is_active'), 'environmental_records', ['is_active'], unique=False)
    op.create_index(op.f('ix_environmental_records_metric_type'), 'environmental_records', ['metric_type'], unique=False)
    op.create_index(op.f('ix_environmental_records_recorded_date'), 'environmental_records', ['recorded_date'], unique=False)
    op.create_index(op.f('ix_environmental_records_user_id'), 'environmental_records', ['user_id'], unique=False)
    op.create_table('governance_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_records_is_active'), 'governance_records', ['is_active'], unique=False)
    op.create_index(op.f('ix_governance_records_metric_type'), 'governance_records', ['metric_type'], unique=False)
    op.create_index(op.f('ix_governance_records_recorded_date'), 'governance_records', ['recorded_date'], unique=False)
    op.create_index(op.f('ix_governance_records_status'), 'governance_records', ['status'], unique=False)
    op.create_index(op.f('ix_governance_records_user_id'), 'governance_records', ['user_id'], unique=False)
    op.create_table('saved_reports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_reports_is_active'), 'saved_reports', ['is_active'], unique=False)
    op.create_index(op.f('ix_saved_reports_report_type'), 'saved_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_saved_reports_user_id'), 'saved_reports', ['user_id'], unique=False)
    op.create_table('social_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_records_is_active'), 'social_records', ['is_active'], unique=False)
    op.create_index(op.f('ix_social_records_metric_type'), 'social_records', ['metric_type'], unique=False)
    op.create_index(op.f('ix_social_records_recorded_date'), 'social_records', ['recorded_date'], unique=False)
    op.create_index(op.f('ix_social_records_user_id'), 'social_records', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_badges_badge_id'), 'user_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_user_badges_is_active'), 'user_badges', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('user_challenges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_challenges_challenge_id'), 'user_challenges', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_user_challenges_is_active'), 'user_challenges', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_challenges_status'), 'user_challenges', ['status'], unique=False)
    op.create_index(op.f('ix_user_challenges_user_id'), 'user_challenges', ['user_id'], unique=False)
    op.create_index(op.f('ix_departments_is_active'), 'departments', ['is_active'], unique=False)
    op.create_index(op.f('ix_roles_is_active'), 'roles', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_index(op.f('ix_roles_is_active'), table_name='roles')
    op.drop_index(op.f('ix_departments_is_active'), table_name='departments')
    op.drop_index(op.f('ix_user_challenges_user_id'), table_name='user_challenges')
    op.drop_index(op.f('ix_user_challenges_status'), table_name='user_challenges')
    op.drop_index(op.f('ix_user_challenges_is_active'), table_name='user_challenges')
    op.drop_index(op.f('ix_user_challenges_challenge_id'), table_name='user_challenges')
    op.drop_table('user_challenges')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_is_active'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_social_records_user_id'), table_name='social_records')
    op.drop_index(op.f('ix_social_records_recorded_date'), table_name='social_records')
    op.drop_index(op.f('ix_social_records_metric_type'), table_name='social_records')
    op.drop_index(op.f('ix_social_records_is_active'), table_name='social_records')
    op.drop_table('social_records')
    op.drop_index(op.f('ix_saved_reports_user_id'), table_name='saved_reports')
    op.drop_index(op.f('ix_saved_reports_report_type'), table_name='saved_reports')
    op.drop_index(op.f('ix_saved_reports_is_active'), table_name='saved_reports')
    op.drop_table('saved_reports')
    op.drop_index(op.f('ix_governance_records_user_id'), table_name='governance_records')
    op.drop_index(op.f('ix_governance_records_status'), table_name='governance_records')
    op.drop_index(op.f('ix_governance_records_recorded_date'), table_name='governance_records')
    op.drop_index(op.f('ix_governance_records_metric_type'), table_name='governance_records')
    op.drop_index(op.f('ix_governance_records_is_active'), table_name='governance_records')
    op.drop_table('governance_records')
    op.drop_index(op.f('ix_environmental_records_user_id'), table_name='environmental_records')
    op.drop_index(op.f('ix_environmental_records_recorded_date'), table_name='environmental_records')
    op.drop_index(op.f('ix_environmental_records_metric_type'), table_name='environmental_records')
    op.drop_index(op.f('ix_environmental_records_is_active'), table_name='environmental_records')
    op.drop_table('environmental_records')
    op.drop_index(op.f('ix_challenges_start_date'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_is_active'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_end_date'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_badges_is_active'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
